services:
  # Base de données pour les données propres (Relational)
  db_postgres:
    image: postgres:16-alpine
    container_name: echoculture_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    container_name: echoculture_adminer
    ports:
      - "8082:8080"
    depends_on:
      - db_postgres

  # Base de données pour le scraping brut (NoSQL)
  db_mongodb:
    image: mongo:7.0
    container_name: echoculture_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo_express:
    image: mongo-express:latest
    container_name: echoculture_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # On utilise le nom du service "db_mongodb" dans l'URL
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db_mongodb:27017/
    depends_on:
      - db_mongodb

  airflow-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    user: root
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - airflow-db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scrapers:/opt/airflow/scrapers
      - ./utils:/opt/airflow/utils
      - ./logs:/opt/airflow/logs
      - ./dbt:/opt/airflow/dbt
      - ./spark:/opt/airflow/spark
    environment:
      LOAD_EX: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  airflow-scheduler:
    build: .
    user: root
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - airflow-db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scrapers:/opt/airflow/scrapers
      - ./utils:/opt/airflow/utils
      - ./logs:/opt/airflow/logs
      - ./dbt:/opt/airflow/dbt
      - ./spark:/opt/airflow/spark
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow
    command: scheduler
  spark:
    image: apache/spark:3.5.1
    container_name: echoculture_spark
    environment:
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "7077:7077"
      - "8085:8080"
    volumes:
      - ./spark:/opt/spark-jobs
    command: >
      /opt/spark/sbin/start-master.sh --host 0.0.0.0 --port 7077 --webui-port 8080

  echoculture-ui:
      build:
        context: .
        dockerfile: app/Dockerfile
        args:
          - API_URL=${API_URL}
      container_name: echoculture-ui
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "3000:3000"
        - "8000:8000"
      environment:
        - API_URL=${API_URL}
        - FRONTEND_URL=${FRONTEND_URL}
        - POSTGRES_URL=${POSTGRES_URL}
        - OLLAMA_URL=${OLLAMA_URL}
      depends_on:
        - db_postgres
      restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: echoculture_cloudflared
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - echoculture-ui
    restart: always

  ollama:
    image: ollama/ollama
    container_name: echoculture_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
volumes:
  pg_data:
  mongo_data:
  airflow_db_data:
  ollama_data:
